# apiVersion: v1
# kind: service
# metadata: 
#   name: Service-nginx
# spec: 
#   container:
#   - name: Service-nginx-con
#     image: nginx 
#     ports:
#     - containerPort: 80

---
apiVersion: v1
kind: pod 
metadata:
  name: pod-name
  labels:
    server: nginx-label
spec:
  container:
    - name: nginx-con
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  server : nginx-service
spec:
  selector:
    name: nginx
  ports:
    - protocol: TCP
      port: 80  #service port
      targetPort: 9376 #container port

---
apiVersion: v1
kind: pod 
metadata:
  name: pod-name
  labels:
    server: almalinux
spec:
  container:
    - name: almalinux
      image: almalinux
      command: ["sleep","1000000"]


