apiVersion: v1
kind: Pod 
metadata:
  name: nginx1
  namespace: session2
spec:
  containers:
    - name: nginx-image 
      image: nginx 
      ports:
        - containerPort: 80 

# kubectl get pods -n session2 <namespace-name> 
# In k8s smallest deployable unit is pod