apiVersion: v1
kind: Pod 
metadata:
  name: image-pull-policy
  namespace: session2
spec:
  containers:
    - name: nginx-image 
      image: nginx 
      imagePullPolicy: Always
      ports:
        - containerPort: 80 