apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    - name: nginx-env
      image: nginx
      env:
        - name: k8s
          value: shiva
        - name: docker
          value: shiva