apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: username
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: PASSWORD 
        valueFrom: 
          secretKeyRef:
            name: mysecret 
            key: password

