apiVersion: v1
kind: Pod 
metadata:
  name: multiconainers
  namespace: session2
spec:
  containers:
    - name: nginx-name
      image: nginx
      ports:
        - containerPort: 80
    - name: sidecar
      image: almalinux #This will pushh all the logs to elk
      command: ["sleep","200"]

      